-- Generated by DBeaver from a database created by sqitch

CREATE TABLE `changes` (
  `change_id` varchar(40) NOT NULL COMMENT 'Change primary key.',
  `script_hash` varchar(40) DEFAULT NULL COMMENT 'Deploy script SHA-1 hash.',
  `change` varchar(255) NOT NULL COMMENT 'Name of a deployed change.',
  `project` varchar(255) NOT NULL COMMENT 'Name of the Sqitch project to which the change belongs.',
  `note` text NOT NULL COMMENT 'Description of the change.',
  `committed_at` datetime(6) NOT NULL COMMENT 'Date the change was deployed.',
  `committer_name` varchar(255) NOT NULL COMMENT 'Name of the user who deployed the change.',
  `committer_email` varchar(255) NOT NULL COMMENT 'Email address of the user who deployed the change.',
  `planned_at` datetime NOT NULL COMMENT 'Date the change was added to the plan.',
  `planner_name` varchar(255) NOT NULL COMMENT 'Name of the user who planed the change.',
  `planner_email` varchar(255) NOT NULL COMMENT 'Email address of the user who planned the change.',
  PRIMARY KEY (`change_id`),
  UNIQUE KEY `project` (`project`,`script_hash`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='Tracks the changes currently deployed to the database.';

CREATE TABLE `events` (
  `event` enum('deploy','fail','merge','revert') NOT NULL COMMENT 'Type of event.',
  `change_id` varchar(40) NOT NULL COMMENT 'Change ID.',
  `change` varchar(255) NOT NULL COMMENT 'Change name.',
  `project` varchar(255) NOT NULL COMMENT 'Name of the Sqitch project to which the change belongs.',
  `note` text NOT NULL COMMENT 'Description of the change.',
  `requires` text NOT NULL COMMENT 'List of the names of required changes.',
  `conflicts` text NOT NULL COMMENT 'List of the names of conflicting changes.',
  `tags` text NOT NULL COMMENT 'List of tags associated with the change.',
  `committed_at` datetime NOT NULL COMMENT 'Date the event was committed.',
  `committer_name` varchar(255) NOT NULL COMMENT 'Name of the user who committed the event.',
  `committer_email` varchar(255) NOT NULL COMMENT 'Email address of the user who committed the event.',
  `planned_at` datetime NOT NULL COMMENT 'Date the event was added to the plan.',
  `planner_name` varchar(255) NOT NULL COMMENT 'Name of the user who planed the change.',
  `planner_email` varchar(255) NOT NULL COMMENT 'Email address of the user who plan planned the change.',
  PRIMARY KEY (`change_id`,`committed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='Contains full history of all deployment events.';
